# Generated by Django 3.2.4 on 2021-07-21 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_product_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_sell',
            field=models.BooleanField(default=False),
        ),
    ]
