# Generated by Django 3.2.4 on 2021-07-21 19:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_product_is_sell'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='is_sell',
            new_name='is_sold',
        ),
    ]
